# Generated by Django 4.2.5 on 2023-09-23 17:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='employees_picture')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('position', models.CharField(choices=[('Manager', 'Manager / CEO / Owner'), ('Counter', 'Counter'), ('SalesMan', 'Sales Man'), ('Steward', 'Steward')], default='SalesMan', max_length=10)),
                ('salary', models.PositiveIntegerField()),
                ('distribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='distribution.distributionprofile')),
            ],
        ),
    ]
