# Generated by Django 4.2.5 on 2023-09-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_employeesprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesprofile',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.distributionprofile'),
        ),
    ]
