# Generated by Django 4.2.5 on 2023-09-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_alter_employeesprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionprofile',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='distributionprofile',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='distributionprofile',
            name='website',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
