# Generated by Django 4.2.5 on 2023-09-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_alter_distributionprofile_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributionprofile',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='distributionprofile',
            old_name='logo',
            new_name='picture',
        ),
    ]
