# Generated by Django 4.2.5 on 2023-09-26 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0006_rename_location_distributionprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='companies_logo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, null=True, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.distributionprofile')),
            ],
        ),
    ]
