# Generated by Django 4.2.5 on 2023-09-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0010_alter_companyprofile_name_productform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
