# Generated by Django 4.2.5 on 2023-10-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0012_alter_productform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
