# Generated by Django 4.2.5 on 2023-10-03 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0013_alter_distributionprofile_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productform',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productform',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='productform',
            name='picture',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='distributionprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='distributionprofile',
            name='warranty',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeesprofile',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productform',
            name='percentage',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='productform',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distributionprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='distributionprofile',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeesprofile',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productform',
            name='category',
            field=models.CharField(choices=[('syp', 'Syrup'), ('tab', 'Tablet'), ('drops', 'Drops'), ('injection', 'Injection'), ('sachet', 'Sachet'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='productform',
            name='price',
            field=models.FloatField(),
        ),
    ]
