# Generated by Django 4.2.5 on 2023-10-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0014_remove_productform_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employeesprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
