# Generated by Django 4.2.6 on 2023-10-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0016_alter_employeesprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
