# Generated by Django 4.2.5 on 2023-10-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('province', models.CharField(choices=[('kpk', ' Khyber Pakhtunkhwa'), ('punjab', 'Punjab'), ('baloch', 'Balochistan'), ('sindh', 'Sindh')], default='kpk', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.area')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.country')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=13)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.area')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.district')),
                ('sub_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.subarea')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='sub_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.subarea'),
        ),
    ]
