# Generated by Django 4.2.5 on 2023-10-06 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_province_remove_district_country_delete_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.province'),
        ),
    ]
