# Generated by Django 4.2.6 on 2023-10-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockproduct_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockproduct',
            old_name='net_price',
            new_name='price',
        ),
    ]
