# Generated by Django 4.2.6 on 2023-10-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_net_price_stockproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproduct',
            name='net_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='price',
            field=models.FloatField(),
        ),
    ]
