# Generated by Django 4.2.6 on 2023-10-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockproduct_net_price_alter_stockproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproduct',
            name='net_price',
        ),
    ]
