# Generated by Django 4.2.6 on 2023-10-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_stockreceipt_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceipt',
            name='discount',
            field=models.FloatField(default='10.0'),
            preserve_default=False,
        ),
    ]
