# Generated by Django 4.2.6 on 2023-10-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockreceipt_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockreceipt',
            old_name='discount',
            new_name='_discount',
        ),
    ]
