# Generated by Django 4.2.6 on 2023-10-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_discount_stockreceipt__discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockreceipt',
            old_name='_discount',
            new_name='discount',
        ),
    ]
