# Generated by Django 4.2.6 on 2023-10-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stockreceipt_invoice_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockreceipt',
            name='invoice_number',
        ),
    ]
