# Generated by Django 4.2.6 on 2023-10-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_stockreceipt_discount_salesinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='total_invoice_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
