# Generated by Django 4.2.6 on 2023-10-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_salesinvoice_total_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='inventory',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
            preserve_default=False,
        ),
    ]
