# Generated by Django 4.2.6 on 2023-10-11 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_salesproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesproduct',
            name='invoice',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='inventory.salesinvoice'),
            preserve_default=False,
        ),
    ]
