# Generated by Django 4.2.6 on 2023-10-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_rename_product_salesproduct_stock_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_invoice_amount',
            field=models.FloatField(null=True),
        ),
    ]
