# Generated by Django 4.2.6 on 2023-10-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_salesinvoice_total_invoice_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_invoice_amount',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
