# Generated by Django 4.2.6 on 2023-10-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0016_alter_employeesprofile_email'),
        ('inventory', '0022_alter_salesinvoice_total_invoice_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_invoice_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='product',
            field=models.ForeignKey(limit_choices_to={'company__user__distribution': True}, on_delete=django.db.models.deletion.CASCADE, to='distribution.productform'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='company',
            field=models.ForeignKey(limit_choices_to={'user__distribution': True}, on_delete=django.db.models.deletion.CASCADE, to='distribution.companyprofile'),
        ),
    ]
