# Generated by Django 4.2.6 on 2023-10-15 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0016_alter_employeesprofile_email'),
        ('customer', '0005_alter_district_province'),
        ('inventory', '0023_alter_salesinvoice_total_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='salesman',
            field=models.ForeignKey(limit_choices_to={'distribution__user': 9}, on_delete=django.db.models.deletion.CASCADE, to='distribution.employeesprofile'),
        ),
        migrations.AlterField(
            model_name='salesproduct',
            name='stock_product',
            field=models.ForeignKey(limit_choices_to={'stock_receipt__inventory__distribution__user': 9}, on_delete=django.db.models.deletion.CASCADE, to='inventory.stockproduct'),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='product',
            field=models.ForeignKey(limit_choices_to={'company__distribution__user': 9}, on_delete=django.db.models.deletion.CASCADE, to='distribution.productform'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='company',
            field=models.ForeignKey(limit_choices_to={'distribution__user_id': 9}, on_delete=django.db.models.deletion.CASCADE, to='distribution.companyprofile'),
        ),
        migrations.CreateModel(
            name='CustomerSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_paid', models.FloatField(default=0.0, null=True)),
                ('total_debt', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('invoice', models.ManyToManyField(to='inventory.salesinvoice')),
            ],
        ),
    ]
