# Generated by Django 4.2.6 on 2023-10-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_salesinvoice_salesman_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersummary',
            old_name='invoice',
            new_name='invoices',
        ),
        migrations.AddField(
            model_name='customersummary',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
