# Generated by Django 4.2.6 on 2023-10-15 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_district_province'),
        ('inventory', '0025_rename_invoice_customersummary_invoices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersummary',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='customersummary',
            name='invoices',
            field=models.ManyToManyField(limit_choices_to={'customer': 3}, to='inventory.salesinvoice'),
        ),
    ]
