# Generated by Django 4.2.6 on 2023-10-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_customersummary_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersummary',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customersummary',
            name='invoices',
            field=models.ManyToManyField(limit_choices_to={'customer': models.IntegerField(default=0)}, null=True, to='inventory.salesinvoice'),
        ),
    ]
