# Generated by Django 4.2.6 on 2023-10-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_customersummary_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersummary',
            name='invoices',
            field=models.ManyToManyField(limit_choices_to={'customer__id': models.F('user_id')}, null=True, to='inventory.salesinvoice'),
        ),
    ]
