# Generated by Django 4.2.6 on 2023-10-16 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0016_alter_employeesprofile_email'),
        ('inventory', '0029_remove_customersummary_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersummary',
            name='invoices',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.salesinvoice'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.employeesprofile'),
        ),
        migrations.AlterField(
            model_name='salesproduct',
            name='stock_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockproduct'),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.productform'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.companyprofile'),
        ),
    ]
