# Generated by Django 4.2.6 on 2023-10-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_alter_customersummary_invoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
