# Generated by Django 4.2.6 on 2023-10-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_salesinvoice_total_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_invoice_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_paid',
            field=models.FloatField(default=0.0),
        ),
    ]
